[mHTTP GET /brewing 200 [0.19, 127.0.0.1:27406][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:27406][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:27406][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:27416]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:27416]
Tue May 31 14:46:53 2022: Another client connected
[mHTTP GET /home 200 [0.06, 127.0.0.1:27518][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:27416]
[mHTTP GET /edit/19 200 [0.07, 127.0.0.1:27527][0m
[mHTTP GET /static/js/edit.js 200 [0.04, 127.0.0.1:27527][0m
[32mHTTP GET /admin 301 [0.16, 127.0.0.1:1261][0m
[mHTTP GET /admin/ 200 [0.70, 127.0.0.1:1261][0m
[mHTTP GET /static/admin/css/base.css 200 [0.06, 127.0.0.1:1261][0m
[mHTTP GET /static/admin/css/dark_mode.css 200 [0.07, 127.0.0.1:1262][0m
[mHTTP GET /static/admin/css/nav_sidebar.css 200 [0.04, 127.0.0.1:1261][0m
[mHTTP GET /static/admin/css/dashboard.css 200 [0.04, 127.0.0.1:1262][0m
[mHTTP GET /static/admin/css/responsive.css 200 [0.04, 127.0.0.1:1261][0m
[mHTTP GET /static/admin/js/nav_sidebar.js 200 [0.03, 127.0.0.1:1261][0m
[mHTTP GET /static/admin/css/fonts.css 200 [0.02, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/img/icon-addlink.svg 200 [0.01, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/img/icon-changelink.svg 200 [0.01, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/img/icon-deletelink.svg 200 [0.01, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.02, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.04, 127.0.0.1:1275][0m
[mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.04, 127.0.0.1:1272][0m
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.10, 127.0.0.1:1272][0m
[mHTTP GET /admin/brewing/brew_recipe/ 200 [0.33, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/css/changelists.css 200 [0.05, 127.0.0.1:1272][0m
[mHTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:1275][0m
[mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.22, 127.0.0.1:1278][0m
[mHTTP GET /static/admin/js/core.js 200 [0.24, 127.0.0.1:1279][0m
[mHTTP GET /static/admin/js/jquery.init.js 200 [0.26, 127.0.0.1:1277][0m
[mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.23, 127.0.0.1:1272][0m
[mHTTP GET /static/admin/js/actions.js 200 [0.22, 127.0.0.1:1275][0m
[mHTTP GET /static/admin/js/urlify.js 200 [0.14, 127.0.0.1:1278][0m
[mHTTP GET /static/admin/js/prepopulate.js 200 [0.12, 127.0.0.1:1279][0m
[mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.18, 127.0.0.1:1282][0m
[mHTTP GET /static/admin/img/tooltag-add.svg 200 [0.02, 127.0.0.1:1282][0m
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [1.12, 127.0.0.1:1282][0m
[mHTTP GET /static/admin/css/forms.css 200 [0.05, 127.0.0.1:1282][0m
[mHTTP GET /admin/jsi18n/ 200 [0.15, 127.0.0.1:1278][0m
[mHTTP GET /static/admin/js/prepopulate_init.js 200 [0.17, 127.0.0.1:1279][0m
[mHTTP GET /static/admin/css/widgets.css 200 [0.06, 127.0.0.1:1279][0m
[mHTTP GET /static/admin/js/change_form.js 200 [0.06, 127.0.0.1:1278][0m
[mHTTP GET /create 200 [0.05, 127.0.0.1:1329][0m
[mHTTP GET /home 200 [0.07, 127.0.0.1:1341][0m
[mHTTP GET /edit/19 200 [0.06, 127.0.0.1:1345][0m
[mHTTP GET /create 200 [0.04, 127.0.0.1:1351][0m
[mHTTP GET /home 200 [0.06, 127.0.0.1:1355][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:1360][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:1360][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1363]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1363]
Tue May 31 15:10:26 2022: Another client connected
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [1.65, 127.0.0.1:1816][0m
[mHTTP GET /admin/jsi18n/ 200 [0.11, 127.0.0.1:1816][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.20, 127.0.0.1:2010][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:2016][0m
[mHTTP GET /brewing 200 [0.11, 127.0.0.1:2016][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2020]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2020]
Tue May 31 15:32:56 2022: Another client connected
Exception inside application: name 'load_phases' is not defined
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 184, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = load_phases(0)
NameError: name 'load_phases' is not defined
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2020]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.29, 127.0.0.1:2085][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:2091][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2091][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2095]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2095]
Tue May 31 15:35:06 2022: Another client connected
Exception inside application: name 'load_phases' is not defined
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 185, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 129, in maischen_procedure
    phases = load_phases(0)
NameError: name 'load_phases' is not defined
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2095]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.26, 127.0.0.1:2255][0m
[32mHTTP POST /brewing 302 [0.07, 127.0.0.1:2255][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2255][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2261]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2261]
Tue May 31 15:40:41 2022: Another client connected
Exception inside application: object of type 'method' has no len()
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 184, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 108, in maischen_procedure
    for i in range(len(phases)):
TypeError: object of type 'method' has no len()
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2261]
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2379]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2379]
Tue May 31 16:17:34 2022: Another client connected
[mHTTP GET /brewing 200 [0.17, 127.0.0.1:27778][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:27782][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:27782][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:27785]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:27785]
Tue May 31 17:52:07 2022: Another client connected
Exception inside application: object of type 'method' has no len()
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 184, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 108, in maischen_procedure
    for i in range(len(phases)):
TypeError: object of type 'method' has no len()
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:27785]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.23, 127.0.0.1:27795][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:27795][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:27795][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:27800]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:27800]
Tue May 31 17:52:47 2022: Another client connected
Exception inside application: Field 'id' expected a number but got [].
Traceback (most recent call last):
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1992, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 185, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 162, in load_phases
    temp = recipe.objects.get(id=id).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 509, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1182, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1200, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1207, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1494, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1524, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1440, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1270, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 340, in get_prep_lookup
    return super().get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1994, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [].
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:27800]
[mHTTP GET /brewing 200 [0.24, 127.0.0.1:27843][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:27851][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:27851][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:27854]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:27854]
Tue May 31 17:56:21 2022: Another client connected
Exception inside application: Field 'id' expected a number but got [].
Traceback (most recent call last):
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1992, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 185, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 162, in load_phases
    temp = recipe.objects.get(id=id).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 509, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1182, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1200, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1207, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1494, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1524, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1440, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1270, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 340, in get_prep_lookup
    return super().get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1994, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [].
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:27854]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.21, 127.0.0.1:27876][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:27882][0m
[mHTTP GET /brewing 200 [0.13, 127.0.0.1:27882][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:27885]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:27885]
Tue May 31 17:57:25 2022: Another client connected
Exception inside application: Field 'id' expected a number but got [].
Traceback (most recent call last):
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1992, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 192, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 169, in load_phases
    temp = recipe.objects.get(id=id).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 509, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1182, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1200, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1207, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1494, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1524, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1440, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1270, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 340, in get_prep_lookup
    return super().get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1994, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [].
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:27885]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.13, 127.0.0.1:27933][0m
[32mHTTP POST /brewing 302 [0.07, 127.0.0.1:27939][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:27939][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:27943]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:27943]
Tue May 31 17:59:43 2022: Another client connected
Exception inside application: Field 'id' expected a number but got [].
Traceback (most recent call last):
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1992, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in load_phases
    temp = recipe.objects.get(id=id).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 509, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1182, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1200, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 1207, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1494, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1524, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1440, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "c:\users\jonas\documents\django\django\django\db\models\sql\query.py", line 1270, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 340, in get_prep_lookup
    return super().get_prep_lookup()
  File "c:\users\jonas\documents\django\django\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "c:\users\jonas\documents\django\django\django\db\models\fields\__init__.py", line 1994, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [].
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:27943]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:27986][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:27996][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:27996][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28000]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28000]
Tue May 31 18:00:49 2022: Another client connected
Exception inside application: 'dict' object has no attribute 'recipe'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 167, in load_phases
    id = self.status.recipe
AttributeError: 'dict' object has no attribute 'recipe'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28000]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.18, 127.0.0.1:28065][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:28065][0m
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:28065][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28072]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28072]
Tue May 31 18:02:37 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in load_phases
    temp = recipe.objects.get(id=id).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28072]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:28113][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:28113][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:28113][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28122]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28122]
Tue May 31 18:03:39 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in load_phases
    temp = recipe.objects.get(id=id).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28122]
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [0.70, 127.0.0.1:28132][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:28132][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:28184][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:28191][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:28191][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28194]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28194]
Tue May 31 18:05:22 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in load_phases
    temp = recipe.objects.get(id=19).maischplan
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28194]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.20, 127.0.0.1:28225][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:28231][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:28231][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28236]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28236]
Tue May 31 18:06:13 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in load_phases
    temp = recipe.objects.get(id=19)
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28236]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.21, 127.0.0.1:28306][0m
[32mHTTP POST /brewing 302 [0.08, 127.0.0.1:28306][0m
[mHTTP GET /brewing 200 [0.09, 127.0.0.1:28306][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28319]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28319]
Tue May 31 18:08:05 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 193, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 104, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in load_phases
    temp = recipe.objects.get(id=int(s_id))
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28319]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:28440][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:28447][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:28447][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28450]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28450]
Tue May 31 18:10:02 2022: Another client connected
Exception inside application: No recipe matches the given query.
Traceback (most recent call last):
  File "c:\users\jonas\documents\django\django\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 195, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 105, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 172, in load_phases
    temp = get_object_or_404(recipe, id=int(s_id))
  File "c:\users\jonas\documents\django\django\django\shortcuts.py", line 87, in get_object_or_404
    raise Http404(
django.http.response.Http404: No recipe matches the given query.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28450]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:28515][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:28515][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:28515][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28523]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28523]
Tue May 31 18:11:46 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:28583][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:28583][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:28583][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28590]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28590]
Tue May 31 18:13:06 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:28629][0m
[32mHTTP POST /brewing 302 [0.07, 127.0.0.1:28638][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:28638][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28641]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28641]
Tue May 31 18:14:13 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:28718][0m
[32mHTTP POST /brewing 302 [0.58, 127.0.0.1:28739][0m
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:28739][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:28744]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:28744]
Tue May 31 18:16:45 2022: Another client connected
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:28744]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.18, 127.0.0.1:1161][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:1170][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:1170][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1175]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1175]
Tue May 31 18:52:24 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 190, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 107, in maischen_procedure
    print(recipe.objects.get(id=19))
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:1175]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.28, 127.0.0.1:1231][0m
[mHTTP GET /brewing?order_by=bier_sorte 200 [0.06, 127.0.0.1:1238][0m
[32mHTTP POST /brewing 302 [0.08, 127.0.0.1:1238][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:1238][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1245]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1245]
Tue May 31 18:53:38 2022: Another client connected
Exception inside application: recipe matching query does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 191, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 108, in maischen_procedure
    print(recipe.objects.get(id='19'))
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 523, in get
    raise self.model.DoesNotExist(
brewing.models.recipe.DoesNotExist: recipe matching query does not exist.
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:1245]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.16, 127.0.0.1:1311][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:1311][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:1311][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1319]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1319]
Tue May 31 18:55:29 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:1429][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:1437][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:1437][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1442]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1442]
Tue May 31 18:58:18 2022: Another client connected
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [1.43, 127.0.0.1:1521][0m
[mHTTP GET /admin/jsi18n/ 200 [0.17, 127.0.0.1:1521][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.17, 127.0.0.1:1654][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:1654][0m
[mHTTP GET /brewing 200 [0.08, 127.0.0.1:1654][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1662]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1662]
Tue May 31 19:04:26 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.13, 127.0.0.1:1700][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:1700][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:1700][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1707]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1707]
Tue May 31 19:05:27 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.13, 127.0.0.1:1740][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:1759][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:1759][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1765]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1765]
Tue May 31 19:06:43 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.19, 127.0.0.1:1831][0m
[32mHTTP POST /brewing 302 [0.06, 127.0.0.1:1831][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:1831][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1838]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1838]
Tue May 31 19:08:19 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.20, 127.0.0.1:2017][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:2017][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2017][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2026]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2026]
Tue May 31 19:13:24 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:2188][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2197][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2197][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2202]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2202]
Tue May 31 19:17:59 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.16, 127.0.0.1:2264][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:2272][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2272][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2276]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2276]
Tue May 31 19:19:43 2022: Another client connected
Exception inside application: the JSON object must be str, bytes or bytearray, not brew_recipe
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 199, in keep_process
    self.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 114, in maischen_procedure
    phases = self.load_phases(0)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 179, in load_phases
    print(json.loads(recipe))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not brew_recipe
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2276]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:2366][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2366][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2366][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2374]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2374]
Tue May 31 19:21:17 2022: Another client connected
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [0.45, 127.0.0.1:2392][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:2392][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:2485][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:2494][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2494][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2498]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2498]
Tue May 31 19:23:59 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.12, 127.0.0.1:2676][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2683][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2683][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2688]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2688]
Tue May 31 19:29:10 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:2718][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:2718][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2718][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2724]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2724]
Tue May 31 19:29:50 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:2749][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2749][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:2749][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2761]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2761]
Tue May 31 19:30:27 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.21, 127.0.0.1:2828][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2843][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2843][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2847]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2847]
Tue May 31 19:32:20 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.13, 127.0.0.1:2933][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:2933][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:2933][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2941]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2941]
Tue May 31 19:34:17 2022: Another client connected
Exception inside application: string index out of range
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 23, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 47, in evaluate_response
    brew_system.keep_process()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 170, in keep_process
    self.kochen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 134, in kochen_procedure
    phases = self.load_phases(1)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 160, in load_phases
    temp = json.loads(recipe.wuerzekochen)[0][2]
IndexError: string index out of range
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2941]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /create 200 [0.96, 127.0.0.1:3054][0m
[mHTTP GET /brewing 200 [0.18, 127.0.0.1:3115][0m
[32mHTTP POST /brewing 302 [0.08, 127.0.0.1:3124][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:3124][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3129]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3129]
Tue May 31 19:39:07 2022: Another client connected
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:3148][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3129]
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3153]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3153]
Tue May 31 19:39:31 2022: Another client connected
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:3160][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3153]
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3163]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3163]
Tue May 31 19:39:36 2022: Another client connected
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:3177][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3163]
[mHTTP GET /static/css/create.css 200 [0.05, 127.0.0.1:3177][0m
[mHTTP GET /static/js/server_connection.js 200 [0.11, 127.0.0.1:3178][0m
[mHTTP GET /static/js/three.js 200 [0.12, 127.0.0.1:3177][0m
[mHTTP GET /static/css/brewing.css 200 [0.01, 127.0.0.1:3177][0m
[mHTTP GET /static/css/home.css 200 [0.01, 127.0.0.1:3177][0m
[mHTTP GET /static/css/template.css 200 [0.04, 127.0.0.1:3177][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3187]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3187]
Tue May 31 19:40:02 2022: Another client connected
[mHTTP GET /static/img/favicon.ico 200 [0.03, 127.0.0.1:3177][0m
[mHTTP GET /static/img/favicon.ico 200 [0.02, 127.0.0.1:3191][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3187]
