C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
[mHTTP GET /brewing 200 [0.12, 127.0.0.1:2685][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:2685][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:2685][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.03, 127.0.0.1:2685][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2693]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2693]
Mon Apr 11 17:56:29 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat(True)
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2693]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:2815][0m
[32mHTTP POST /brewing 302 [0.02, 127.0.0.1:2823][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:2823][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.06, 127.0.0.1:2823][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:2826]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:2826]
Mon Apr 11 17:59:18 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat(True)
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:2826]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
[mHTTP GET /brewing 200 [0.15, 127.0.0.1:3017][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:3027][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:3027][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.04, 127.0.0.1:3027][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3031]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3031]
Mon Apr 11 18:02:50 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat(True)
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3031]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.26, 127.0.0.1:3214][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:3214][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:3214][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.12, 127.0.0.1:3214][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3221]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3221]
Mon Apr 11 18:06:17 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat(1)
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3221]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.11, 127.0.0.1:3280][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:3292][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:3292][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3296]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3296]
Mon Apr 11 18:07:26 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat(1)
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3296]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.20, 127.0.0.1:3357][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:3357][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:3357][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3366]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3366]
Mon Apr 11 18:08:51 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat()
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3366]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:3424][0m
[32mHTTP POST /brewing 302 [0.05, 127.0.0.1:3424][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:3424][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.04, 127.0.0.1:3424][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3430]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3430]
Mon Apr 11 18:10:13 2022: Another client connected
Exception inside application: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 96, in maischen_procedure
    self.heat(phases[0][0])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 118, in heat
    self.hardware.heat()
TypeError: 'bool' object is not callable
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:3430]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:3568][0m
[32mHTTP POST /brewing 302 [0.02, 127.0.0.1:3568][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:3568][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3576]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3576]
Mon Apr 11 18:13:12 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\hardware.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.12, 127.0.0.1:3801][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:3811][0m
[mHTTP GET /brewing 200 [0.07, 127.0.0.1:3811][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.04, 127.0.0.1:3811][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3814]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3814]
Mon Apr 11 18:18:05 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.12, 127.0.0.1:3969][0m
[32mHTTP POST /brewing 302 [0.02, 127.0.0.1:3977][0m
[mHTTP GET /brewing 200 [0.03, 127.0.0.1:3977][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:3985]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:3985]
Mon Apr 11 18:21:47 2022: Another client connected
[mHTTP GET /brewing 200 [0.18, 127.0.0.1:25982][0m
[32mHTTP POST /brewing 302 [0.02, 127.0.0.1:25995][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:25995][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.05, 127.0.0.1:25995][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:25999]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:25999]
Mon Apr 11 18:42:46 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.10, 127.0.0.1:26128][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:26138][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:26138][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26142]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26142]
Mon Apr 11 18:45:11 2022: Another client connected
Exception inside application: 'senso_data'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 88, in maischen_procedure
    self.status["senso_data"]["engine_mode"] = False
KeyError: 'senso_data'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:26142]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.26, 127.0.0.1:26185][0m
[32mHTTP POST /brewing 302 [0.02, 127.0.0.1:26193][0m
[mHTTP GET /brewing 200 [0.03, 127.0.0.1:26193][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26197]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26197]
Mon Apr 11 18:46:15 2022: Another client connected
Exception inside application: 'senso_data'
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 87, in maischen_procedure
    self.status["senso_data"]["engine_mode"] = False
KeyError: 'senso_data'
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:26197]
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.14, 127.0.0.1:26262][0m
[32mHTTP POST /brewing 302 [0.02, 127.0.0.1:26269][0m
[mHTTP GET /brewing 200 [0.03, 127.0.0.1:26269][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26274]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26274]
Mon Apr 11 18:47:25 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.16, 127.0.0.1:26419][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:26419][0m
[mHTTP GET /brewing 200 [0.06, 127.0.0.1:26419][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.05, 127.0.0.1:26419][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26429]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26429]
Mon Apr 11 18:50:51 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /admin/brewing/brew_recipe/19/change/ 200 [0.52, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/css/base.css 200 [0.02, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/css/dark_mode.css 200 [0.03, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/css/nav_sidebar.css 200 [0.04, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/css/forms.css 200 [0.05, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/css/responsive.css 200 [0.04, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.03, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/js/jquery.init.js 200 [0.02, 127.0.0.1:26534][0m
[mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/js/core.js 200 [0.02, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.02, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/js/actions.js 200 [0.03, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/js/urlify.js 200 [0.03, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/js/prepopulate.js 200 [0.04, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.03, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/js/prepopulate_init.js 200 [0.03, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/css/fonts.css 200 [0.01, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/css/widgets.css 200 [0.03, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/js/nav_sidebar.js 200 [0.01, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/js/change_form.js 200 [0.02, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/img/icon-addlink.svg 200 [0.01, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.02, 127.0.0.1:26534][0m
[mHTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.03, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.04, 127.0.0.1:26540][0m
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.06, 127.0.0.1:26540][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.16, 127.0.0.1:26540][0m
[mHTTP GET /static/admin/css/changelists.css 200 [0.03, 127.0.0.1:26540][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:26535][0m
[mHTTP GET /static/admin/img/tooltag-add.svg 200 [0.01, 127.0.0.1:26535][0m
[mHTTP POST /admin/brewing/messurement/ 200 [0.14, 127.0.0.1:26556][0m
[mHTTP GET /static/admin/js/cancel.js 200 [0.01, 127.0.0.1:26556][0m
[32mHTTP POST /admin/brewing/messurement/ 302 [0.10, 127.0.0.1:26556][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.11, 127.0.0.1:26556][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:26556][0m
[mHTTP GET /static/admin/img/icon-yes.svg 200 [0.01, 127.0.0.1:26556][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:26567][0m
[32mHTTP POST /brewing 302 [0.03, 127.0.0.1:26574][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:26574][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26577]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26577]
Mon Apr 11 18:53:00 2022: Another client connected
Exception inside application: create() takes 1 positional argument but 4 were given
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 22, in receive
    self.evaluate_response(text_data_json)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 45, in evaluate_response
    brew_system.maischen_procedure()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 120, in maischen_procedure
    self.write_sensor_data()
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 77, in write_sensor_data
    messurement.objects.create(self.status["sensor_data"]["temperature"], self.status["sensor_data"]["engine_mode"], self.status["sensor_data"]["plato"])
  File "c:\users\jonas\documents\django\django\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
TypeError: create() takes 1 positional argument but 4 were given
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:26577]
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.25, 127.0.0.1:26681][0m
[mHTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:26681][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /brewing 200 [0.12, 127.0.0.1:26769][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:26769][0m
[mHTTP GET /brewing 200 [0.04, 127.0.0.1:26769][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26777]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26777]
Mon Apr 11 18:56:31 2022: Another client connected
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:26805][0m
[mHTTP POST /evaluate 200 [0.04, 127.0.0.1:26817][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.24, 127.0.0.1:26817][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:26817][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP POST /evaluate 200 [0.10, 127.0.0.1:26884][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.09, 127.0.0.1:26916][0m
[mHTTP POST /evaluate 200 [0.07, 127.0.0.1:26922][0m
[mHTTP POST /admin/brewing/messurement/ 200 [0.14, 127.0.0.1:26941][0m
[32mHTTP POST /admin/brewing/messurement/ 302 [0.18, 127.0.0.1:26946][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.11, 127.0.0.1:26946][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:26946][0m
[mHTTP GET /brewing 200 [0.05, 127.0.0.1:26953][0m
[32mHTTP POST /brewing 302 [0.04, 127.0.0.1:26961][0m
[mHTTP GET /brewing 200 [0.03, 127.0.0.1:26961][0m
[36mHTTP GET /static/js/server_connection.js 304 [0.03, 127.0.0.1:26961][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:26966]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:26966]
Mon Apr 11 18:59:26 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.11, 127.0.0.1:27022][0m
[mHTTP POST /evaluate 200 [0.09, 127.0.0.1:27030][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:27084][0m
[mHTTP POST /evaluate 200 [0.08, 127.0.0.1:27095][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:27107][0m
[mHTTP POST /evaluate 200 [0.06, 127.0.0.1:27107][0m
