[mHTTP GET /dashboard 200 [0.16, 127.0.0.1:20177][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:20184]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:20184]
Sat Mar 12 14:23:36 2022: Another client connected
Not Found: /favicon.ico
[33mHTTP GET /favicon.ico 404 [0.20, 127.0.0.1:20177][0m
[mHTTP GET /evaluate 200 [0.12, 127.0.0.1:20208][0m
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:20184]
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:20385][0m
[mHTTP GET /evaluate 200 [0.08, 127.0.0.1:20508][0m
[mHTTP GET /admin/ 200 [0.26, 127.0.0.1:20515][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.31, 127.0.0.1:20522][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20522][0m
[mHTTP POST /admin/brewing/messurement/ 200 [0.10, 127.0.0.1:20527][0m
[mHTTP GET /static/admin/js/cancel.js 200 [0.03, 127.0.0.1:20527][0m
[32mHTTP POST /admin/brewing/messurement/ 302 [0.14, 127.0.0.1:20527][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.17, 127.0.0.1:20527][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:20527][0m
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 16, in evaluate
    for i in range(steps_number[0]['step']):
  File "c:\users\jonas\documents\django\django\django\db\models\query.py", line 363, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[35;1mHTTP GET /evaluate 500 [0.47, 127.0.0.1:20527][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.19, 127.0.0.1:20532][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20532][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.08, 127.0.0.1:20536][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.20, 127.0.0.1:20536][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20536][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.14, 127.0.0.1:20536][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20536][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.08, 127.0.0.1:20542][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.19, 127.0.0.1:20542][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20542][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.16, 127.0.0.1:20546][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:20546][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.05, 127.0.0.1:20546][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.19, 127.0.0.1:20546][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:20546][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.16, 127.0.0.1:20550][0m
[mHTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:20550][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.05, 127.0.0.1:20556][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.23, 127.0.0.1:20556][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:20556][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:20556][0m
[mHTTP GET /evaluate 200 [0.11, 127.0.0.1:1903][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:1926][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.12, 127.0.0.1:1967][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:1976][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.19, 127.0.0.1:1992][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1992][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.05, 127.0.0.1:1999][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.22, 127.0.0.1:1999][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1999][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:2005][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.15, 127.0.0.1:2040][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 17, in evaluate
    for i in range(steps_number[0]):
TypeError: 'dict' object cannot be interpreted as an integer
[35;1mHTTP GET /evaluate 500 [0.25, 127.0.0.1:2107][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 17, in evaluate
    for i in range(steps_number):
TypeError: 'QuerySet' object cannot be interpreted as an integer
[35;1mHTTP GET /evaluate 500 [0.24, 127.0.0.1:2141][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.14, 127.0.0.1:2165][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.14, 127.0.0.1:2216][0m
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 31, in evaluate
    return render(request, 'brewing/evaluate.html', {
  File "c:\users\jonas\documents\django\django\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\jonas\documents\django\django\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\jonas\documents\django\django\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\jonas\documents\django\django\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\jonas\documents\django\django\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\jonas\documents\django\django\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\jonas\documents\django\django\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\jonas\documents\django\django\django\template\defaulttags.py", line 853, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "c:\users\jonas\documents\django\django\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['pretty']' from 'dates['pretty']'
[35;1mHTTP GET /evaluate 500 [0.30, 127.0.0.1:2282][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.15, 127.0.0.1:2378][0m
[mHTTP POST /evaluate 200 [0.04, 127.0.0.1:2387][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.24, 127.0.0.1:2387][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:2387][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.07, 127.0.0.1:2402][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.23, 127.0.0.1:2402][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:2402][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:2402][0m
[mHTTP POST /evaluate 200 [0.04, 127.0.0.1:2409][0m
[mHTTP POST /evaluate 200 [0.03, 127.0.0.1:2421][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.14, 127.0.0.1:2421][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:2421][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.06, 127.0.0.1:2434][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.24, 127.0.0.1:2434][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:2434][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:2434][0m
[mHTTP GET /evaluate 200 [0.19, 127.0.0.1:2822][0m
[mHTTP GET /evaluate 200 [0.09, 127.0.0.1:2857][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:2877][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:2900][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:2994][0m
Not Found: /$bg-url
[33mHTTP GET /$bg-url 404 [0.19, 127.0.0.1:2994][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:3019][0m
Not Found: /$bg-url
[33mHTTP GET /$bg-url 404 [0.05, 127.0.0.1:3019][0m
[mHTTP GET /evaluate 200 [0.04, 127.0.0.1:3072][0m
[mHTTP GET /evaluate 200 [0.31, 127.0.0.1:1038][0m
[mHTTP POST /evaluate 200 [0.07, 127.0.0.1:1061][0m
[mHTTP GET /evaluate 200 [0.09, 127.0.0.1:1115][0m
[mHTTP GET /evaluate 200 [0.17, 127.0.0.1:1132][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:1041][0m
[mHTTP GET /evaluate 200 [0.06, 127.0.0.1:1065][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1143][0m
[mHTTP GET /evaluate 200 [0.33, 127.0.0.1:1161][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1173][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1258][0m
[mHTTP GET /evaluate 200 [0.08, 127.0.0.1:1282][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:1292][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1297][0m
[mHTTP POST /evaluate 200 [0.47, 127.0.0.1:1315][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.19, 127.0.0.1:1795][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.28, 127.0.0.1:1800][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:1800][0m
[mHTTP GET /admin/brewing/messurement/add/ 200 [0.17, 127.0.0.1:1805][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1805][0m
[32mHTTP POST /admin/brewing/messurement/add/ 302 [0.10, 127.0.0.1:1811][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.29, 127.0.0.1:1811][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1811][0m
[mHTTP GET /admin/brewing/messurement/15/change/ 200 [0.26, 127.0.0.1:1816][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1816][0m
[32mHTTP POST /admin/brewing/messurement/15/change/ 302 [0.06, 127.0.0.1:1816][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.26, 127.0.0.1:1816][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:1816][0m
[mHTTP GET /evaluate 200 [0.05, 127.0.0.1:1816][0m
[mHTTP POST /evaluate 200 [0.05, 127.0.0.1:1824][0m
[mHTTP GET /admin/brewing/messurement/15/change/ 200 [0.36, 127.0.0.1:1832][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:1832][0m
[32mHTTP POST /admin/brewing/messurement/15/change/ 302 [0.05, 127.0.0.1:1832][0m
[mHTTP GET /admin/brewing/messurement/ 200 [0.21, 127.0.0.1:1832][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:1832][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.12, 127.0.0.1:1868][0m
Internal Server Error: /evaluate
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "c:\users\jonas\documents\django\django\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\jonas\documents\django\django\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py", line 39, in evaluate
    for mode in messurement.objects.filter(step=step).values('engine'):
UnboundLocalError: local variable 'step' referenced before assignment
[35;1mHTTP POST /evaluate 500 [0.23, 127.0.0.1:1877][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\views.py changed, reloading.
[mHTTP GET /evaluate 200 [0.12, 127.0.0.1:1901][0m
[mHTTP POST /evaluate 200 [0.08, 127.0.0.1:1911][0m
[mHTTP GET /evaluate 200 [0.07, 127.0.0.1:1952][0m
[mHTTP POST /evaluate 200 [0.07, 127.0.0.1:1960][0m
[mHTTP GET /evaluate 200 [0.08, 127.0.0.1:1979][0m
[mHTTP POST /evaluate 200 [0.06, 127.0.0.1:1979][0m
[mHTTP POST /evaluate 200 [0.05, 127.0.0.1:1990][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /dashboard 200 [0.08, 127.0.0.1:17269][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17272]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17272]
Sat Mar 12 16:43:48 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /dashboard 200 [0.05, 127.0.0.1:17279][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:17282]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:17282]
Sat Mar 12 16:44:57 2022: Another client connected
Exception inside application: Expecting property name enclosed in double quotes: line 1 column 501 (char 500)
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\consumer.py", line 125, in dispatch
    handler(message)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\channels\generic\websocket.py", line 59, in websocket_receive
    self.receive(text_data=message["text"])
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 24, in receive
    self.evaluate_response(message)
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\consumer.py", line 46, in evaluate_response
    brew_server.load_recipe(1)      #add real recipe id
  File "C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py", line 38, in load_recipe
    self.recipe = json.loads(recipe.objects.get(id=recipe_id).recipe)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 501 (char 500)
WebSocket DISCONNECT /ws/socket-server/ [127.0.0.1:17282]
[mHTTP GET /admin/brewing/messurement/ 200 [0.46, 127.0.0.1:17285][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:17285][0m
[mHTTP GET /admin/brewing/recipe/ 200 [0.14, 127.0.0.1:17285][0m
[mHTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:17285][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\models.py changed, reloading.
[mHTTP GET /admin/brewing/messurement/ 200 [0.43, 127.0.0.1:17321][0m
[mHTTP GET /admin/jsi18n/ 200 [0.06, 127.0.0.1:17321][0m
[mHTTP GET /admin/brewing/recipe/ 200 [0.15, 127.0.0.1:17321][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:17321][0m
[mHTTP GET /admin/brewing/recipe/1/change/ 200 [0.27, 127.0.0.1:12349][0m
[mHTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:12349][0m
[32mHTTP POST /admin/brewing/recipe/1/change/ 302 [0.10, 127.0.0.1:12355][0m
[mHTTP GET /admin/brewing/recipe/ 200 [0.18, 127.0.0.1:12355][0m
[mHTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:12355][0m
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /dashboard 200 [0.06, 127.0.0.1:12368][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:12374]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:12374]
Sat Mar 12 16:49:01 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /dashboard 200 [0.09, 127.0.0.1:1036][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1039]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1039]
Sat Mar 12 16:50:26 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
[mHTTP GET /dashboard 200 [0.06, 127.0.0.1:1054][0m
WebSocket HANDSHAKING /ws/socket-server/ [127.0.0.1:1058]
WebSocket CONNECT /ws/socket-server/ [127.0.0.1:1058]
Sat Mar 12 16:51:09 2022: Another client connected
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
C:\Users\Jonas\Documents\django\brew_seminar\brewing\process\brew_server.py changed, reloading.
